# Generated by Django 4.1 on 2025-01-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time_stay',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Время на сайте'),
        ),
    ]
