# Generated by Django 4.1 on 2024-12-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('resume', models.FileField(null=True, upload_to='', verbose_name='Файл резюме')),
            ],
            options={
                'verbose_name': "Блок 'Обо мне'",
                'verbose_name_plural': "Блок 'Обо мне'",
            },
        ),
    ]
