# Generated by Django 4.1 on 2024-12-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Название')),
                ('file', models.ImageField(upload_to='images', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub')),
                ('link_site', models.URLField(blank=True, null=True, verbose_name='ССылка на сайт')),
                ('images', models.ManyToManyField(to='main.image', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
