# Generated by Django 4.1 on 2025-01-25 00:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_badge_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='link',
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='badge',
            name='logo',
            field=models.ImageField(null=True, upload_to='badges', verbose_name='Лого технологии'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=360, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(help_text='Используй |, чтобы создать абзацы', max_length=700, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='detail',
            field=models.TextField(max_length=250, verbose_name='Подробности'),
        ),
    ]
