# Generated by Django 4.1 on 2025-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_badge_link_badge_color_badge_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='position',
            field=models.IntegerField(null=True, unique=True, verbose_name='Позиция'),
        ),
    ]
