# Generated by Django 4.1 on 2025-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tech_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(null=True, unique=True, verbose_name='Позиция'),
        ),
    ]
