# Generated by Django 5.2.1 on 2025-05-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': "Блок 'Обо мне'"},
        ),
    ]
