# Generated by Django 5.2.1 on 2025-05-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('github_url', models.URLField(verbose_name='Ссылка на GitHub')),
            ],
            options={
                'verbose_name': 'Контактная информация',
            },
        ),
    ]
